### ISSUE TITLE
using the script

### ISSUE THREAD

**Issue by Halo-5** [edent/Fronius-DataManager-Solar-Logger#1]
I am a noob so be kind. The script is php but you state that it can be run as a cron job. How do I run php on a mac terminal?

I wonder if there is a python translation available? That way my pi can run it on my lan without having to set up a web server. I am not interested in exposing my self to the internet.

**Comment by edent** [comment]
> I am a noob so be kind. 

I'll do my best :-)

> How do I run php on a mac terminal?

I don't use a Mac, but I assume just running `php filename.php` should be sufficient. You can then stick that in cron if you want.

> I wonder if there is a python translation available?

I haven't written one, happy to do so in return for a gift from my wishlist - http://www.amazon.co.uk/gp/registry/wishlist/13GFCFR2B2IX4

> That way my pi can run it on my lan without having to set up a web server.

I _think_ you can run PHP on a Pi **without** running a web server like Apache.  Try running `php` on the command line to see if you already have it installed.  Or `sudo apt-get install php` to install it.

**Comment by Halo-5** [comment]
i'll be a monkey's uncle! you can run php from the command line! who knew.?
I noticed you are a scalzi fan. So am i. Please partake of this

**Comment by edent** [comment]
If you're a fan, please encourage people to buy his works - not pirate them.
